### ISSUE TITLE
Where is source code

### ISSUE THREAD

**Issue by paratoner** [OpenSharp/NNugets#1]
How can i find source code ?
Please help :(
i spent 7 days for connect to coherence cluster. İ want to debug this dll because it does not show logical stack trace. Please help

**Comment by asd-and-Rizzo** [comment]
There is no source. It is Oracle dlls, I just put these onto nuget.  Try some decompiler with debug support. Or decompile into C# and compile again.  Try to install dlls from links  https://github.com/OpenSharp/NNugets/tree/master/OracleCoherence to Oracle installer. Validate your xml client config.  Are you on Windows?

**Comment by asd-and-Rizzo** [comment]
Please write email to oracle to open source clients. Thanks.
